In [1]:
import numpy as np

In [3]:
n, m, l = 4, 3, 2
a = np.arange(n*m*l).reshape(n, m, l)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [14]:
b = np.sum(a**2, axis=2)
b

array([[   1,   13,   41],
       [  85,  145,  221],
       [ 313,  421,  545],
       [ 685,  841, 1013]])

In [20]:
c = np.repeat(b[:, :, np.newaxis], 3, axis=2)
d = np.transpose(c, (0, 2, 1))
print(c)
print(d)

[[[   1    1    1]
  [  13   13   13]
  [  41   41   41]]

 [[  85   85   85]
  [ 145  145  145]
  [ 221  221  221]]

 [[ 313  313  313]
  [ 421  421  421]
  [ 545  545  545]]

 [[ 685  685  685]
  [ 841  841  841]
  [1013 1013 1013]]]
[[[   1   13   41]
  [   1   13   41]
  [   1   13   41]]

 [[  85  145  221]
  [  85  145  221]
  [  85  145  221]]

 [[ 313  421  545]
  [ 313  421  545]
  [ 313  421  545]]

 [[ 685  841 1013]
  [ 685  841 1013]
  [ 685  841 1013]]]


In [22]:
a[0] @ a[0].T

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [25]:
e = np.einsum("ijk,ilk->ijl", a, a)

In [28]:
f = c - 2*e + d
f

array([[[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]]])

In [64]:
tmp1, tmp2 = np.triu_indices(3, k=1)
print(tmp1)
i = np.repeat(np.arange(4), [3]), np.tile(tmp1, 4), np.tile(tmp2, 4)
i

[0 0 1]


(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]),
 array([1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2]))

In [59]:
np.triu_indices(3, k=1)

(array([0, 0, 1]), array([1, 2, 2]))

In [60]:
f[np.triu_indices(3, k=1)]

array([[ 8,  0,  8],
       [32,  8,  0],
       [32,  8,  0]])

In [61]:
f

array([[[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]],

       [[ 0,  8, 32],
        [ 8,  0,  8],
        [32,  8,  0]]])

In [66]:
f[i].reshape(4, 3*2//2)

array([[ 8, 32,  8],
       [ 8, 32,  8],
       [ 8, 32,  8],
       [ 8, 32,  8]])

In [34]:
f[, np.triu_indices(3, k=1)]

array([[[[ 0,  8, 32],
         [ 0,  8, 32],
         [ 8,  0,  8]],

        [[ 8,  0,  8],
         [32,  8,  0],
         [32,  8,  0]]],


       [[[ 0,  8, 32],
         [ 0,  8, 32],
         [ 8,  0,  8]],

        [[ 8,  0,  8],
         [32,  8,  0],
         [32,  8,  0]]],


       [[[ 0,  8, 32],
         [ 0,  8, 32],
         [ 8,  0,  8]],

        [[ 8,  0,  8],
         [32,  8,  0],
         [32,  8,  0]]],


       [[[ 0,  8, 32],
         [ 0,  8, 32],
         [ 8,  0,  8]],

        [[ 8,  0,  8],
         [32,  8,  0],
         [32,  8,  0]]]])